plugins {
    id 'groovy'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    jcenter()
    mavenCentral()
}

def _group = 'com.craigburke.angular'
def _version ='4.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

group = "$_group"
version = "$_version"

dependencies {
    compileOnly 'com.bertramlabs.plugins:asset-pipeline-core:4.3.0'
    compileOnly 'org.codehaus.groovy:groovy-all:3.0.13'
    implementation 'org.mozilla:rhino:1.7R4'
    implementation 'com.googlecode.htmlcompressor:htmlcompressor:1.5.2'

    testImplementation 'com.bertramlabs.plugins:asset-pipeline-core:4.3.0'
    testImplementation 'org.spockframework:spock-core:2.3-groovy-3.0'
}

task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from 'build/docs/javadoc'
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

publishing {
    repositories {
        maven {
            url = 'file:///C:/EGS/proprietary.maven.dependencies'
        }
        mavenLocal()
    }
    publications {
        mavenJava(MavenPublication) {
            groupId = "$_group"
            artifactId = 'angular-template-asset-pipeline'
            version = "$_version"

            from components.java

            artifact sourcesJar
        }
    }
}